/**
* | output |
* | --- |
* | "MDXForge" |
*
* @param {Site_NameInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const site_name: ((inputs?: Site_NameInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Site_NameInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "MDXForge - Local-first MDX preview for AI docs" |
*
* @param {Site_TitleInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const site_title: ((inputs?: Site_TitleInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Site_TitleInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "MDXForge is a local-first desktop workspace for safely previewing AI-generated MDX and Markdown documents." |
*
* @param {Site_DescriptionInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const site_description: ((inputs?: Site_DescriptionInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Site_DescriptionInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "404" |
*
* @param {Not_Found_LabelInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const not_found_label: ((inputs?: Not_Found_LabelInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Not_Found_LabelInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Page not found" |
*
* @param {Not_Found_TitleInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const not_found_title: ((inputs?: Not_Found_TitleInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Not_Found_TitleInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "The page you are looking for does not exist yet." |
*
* @param {Not_Found_DescriptionInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const not_found_description: ((inputs?: Not_Found_DescriptionInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Not_Found_DescriptionInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Switch language" |
*
* @param {Language_SwitcherInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const language_switcher: ((inputs?: Language_SwitcherInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Language_SwitcherInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "English" |
*
* @param {Language_EnInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const language_en: ((inputs?: Language_EnInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Language_EnInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "中文" |
*
* @param {Language_ZhInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const language_zh: ((inputs?: Language_ZhInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Language_ZhInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "MDXForge - Preview AI-generated MDX locally" |
*
* @param {Home_Meta_TitleInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_meta_title: ((inputs?: Home_Meta_TitleInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Meta_TitleInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "A focused desktop reader for opening, navigating, and safely rendering local MDX and Markdown files generated by AI." |
*
* @param {Home_Meta_DescriptionInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_meta_description: ((inputs?: Home_Meta_DescriptionInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Meta_DescriptionInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Local-first MDX preview for AI docs" |
*
* @param {Home_BadgeInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_badge: ((inputs?: Home_BadgeInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_BadgeInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Turn AI-generated MDX into a safe local reading experience." |
*
* @param {Home_TitleInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_title: ((inputs?: Home_TitleInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_TitleInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "MDXForge focuses on one workflow: generate structured MDX or Markdown with AI, open it locally, review it comfortably, and share it with confidence." |
*
* @param {Home_DescriptionInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_description: ((inputs?: Home_DescriptionInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_DescriptionInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "View GitHub" |
*
* @param {Home_GithubInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_github: ((inputs?: Home_GithubInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_GithubInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Explore features" |
*
* @param {Home_Features_LinkInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_features_link: ((inputs?: Home_Features_LinkInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Features_LinkInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Open local MDX" |
*
* @param {Home_Feature_Local_TitleInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_feature_local_title: ((inputs?: Home_Feature_Local_TitleInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Feature_Local_TitleInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Preview .mdx and .md files from your machine without publishing them to a cloud service." |
*
* @param {Home_Feature_Local_DescriptionInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_feature_local_description: ((inputs?: Home_Feature_Local_DescriptionInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Feature_Local_DescriptionInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Docs-like reading UI" |
*
* @param {Home_Feature_Docs_TitleInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_feature_docs_title: ((inputs?: Home_Feature_Docs_TitleInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Feature_Docs_TitleInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Render AI-generated documents with a polished navigation, outline, and reading experience." |
*
* @param {Home_Feature_Docs_DescriptionInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_feature_docs_description: ((inputs?: Home_Feature_Docs_DescriptionInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Feature_Docs_DescriptionInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Controlled rendering" |
*
* @param {Home_Feature_Safe_TitleInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_feature_safe_title: ((inputs?: Home_Feature_Safe_TitleInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Feature_Safe_TitleInputs, {
    locale?: "en" | "zh";
}, {}>;
/**
* | output |
* | --- |
* | "Use a curated component surface so generated MDX stays safe, predictable, and reviewable." |
*
* @param {Home_Feature_Safe_DescriptionInputs} inputs
* @param {{ locale?: "en" | "zh" }} options
* @returns {LocalizedString}
*/
export const home_feature_safe_description: ((inputs?: Home_Feature_Safe_DescriptionInputs, options?: {
    locale?: "en" | "zh";
}) => LocalizedString) & import("../runtime.js").MessageMetadata<Home_Feature_Safe_DescriptionInputs, {
    locale?: "en" | "zh";
}, {}>;
export type LocalizedString = import("../runtime.js").LocalizedString;
export type Site_NameInputs = {};
export type Site_TitleInputs = {};
export type Site_DescriptionInputs = {};
export type Not_Found_LabelInputs = {};
export type Not_Found_TitleInputs = {};
export type Not_Found_DescriptionInputs = {};
export type Language_SwitcherInputs = {};
export type Language_EnInputs = {};
export type Language_ZhInputs = {};
export type Home_Meta_TitleInputs = {};
export type Home_Meta_DescriptionInputs = {};
export type Home_BadgeInputs = {};
export type Home_TitleInputs = {};
export type Home_DescriptionInputs = {};
export type Home_GithubInputs = {};
export type Home_Features_LinkInputs = {};
export type Home_Feature_Local_TitleInputs = {};
export type Home_Feature_Local_DescriptionInputs = {};
export type Home_Feature_Docs_TitleInputs = {};
export type Home_Feature_Docs_DescriptionInputs = {};
export type Home_Feature_Safe_TitleInputs = {};
export type Home_Feature_Safe_DescriptionInputs = {};
