/* eslint-disable */
/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */
/** @typedef {{}} Site_NameInputs */
/** @typedef {{}} Site_TitleInputs */
/** @typedef {{}} Site_DescriptionInputs */
/** @typedef {{}} Not_Found_LabelInputs */
/** @typedef {{}} Not_Found_TitleInputs */
/** @typedef {{}} Not_Found_DescriptionInputs */
/** @typedef {{}} Language_SwitcherInputs */
/** @typedef {{}} Language_EnInputs */
/** @typedef {{}} Language_ZhInputs */
/** @typedef {{}} Home_Meta_TitleInputs */
/** @typedef {{}} Home_Meta_DescriptionInputs */
/** @typedef {{}} Home_BadgeInputs */
/** @typedef {{}} Home_TitleInputs */
/** @typedef {{}} Home_DescriptionInputs */
/** @typedef {{}} Home_GithubInputs */
/** @typedef {{}} Home_Features_LinkInputs */
/** @typedef {{}} Home_Feature_Local_TitleInputs */
/** @typedef {{}} Home_Feature_Local_DescriptionInputs */
/** @typedef {{}} Home_Feature_Docs_TitleInputs */
/** @typedef {{}} Home_Feature_Docs_DescriptionInputs */
/** @typedef {{}} Home_Feature_Safe_TitleInputs */
/** @typedef {{}} Home_Feature_Safe_DescriptionInputs */


export const site_name = /** @type {(inputs: Site_NameInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`MDXForge`)
};

export const site_title = /** @type {(inputs: Site_TitleInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`MDXForge - Local-first MDX preview for AI docs`)
};

export const site_description = /** @type {(inputs: Site_DescriptionInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`MDXForge is a local-first desktop workspace for safely previewing AI-generated MDX and Markdown documents.`)
};

export const not_found_label = /** @type {(inputs: Not_Found_LabelInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`404`)
};

export const not_found_title = /** @type {(inputs: Not_Found_TitleInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Page not found`)
};

export const not_found_description = /** @type {(inputs: Not_Found_DescriptionInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The page you are looking for does not exist yet.`)
};

export const language_switcher = /** @type {(inputs: Language_SwitcherInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Switch language`)
};

export const language_en = /** @type {(inputs: Language_EnInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`English`)
};

export const language_zh = /** @type {(inputs: Language_ZhInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`中文`)
};

export const home_meta_title = /** @type {(inputs: Home_Meta_TitleInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`MDXForge - Preview AI-generated MDX locally`)
};

export const home_meta_description = /** @type {(inputs: Home_Meta_DescriptionInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A focused desktop reader for opening, navigating, and safely rendering local MDX and Markdown files generated by AI.`)
};

export const home_badge = /** @type {(inputs: Home_BadgeInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Local-first MDX preview for AI docs`)
};

export const home_title = /** @type {(inputs: Home_TitleInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Turn AI-generated MDX into a safe local reading experience.`)
};

export const home_description = /** @type {(inputs: Home_DescriptionInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`MDXForge focuses on one workflow: generate structured MDX or Markdown with AI, open it locally, review it comfortably, and share it with confidence.`)
};

export const home_github = /** @type {(inputs: Home_GithubInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`View GitHub`)
};

export const home_features_link = /** @type {(inputs: Home_Features_LinkInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Explore features`)
};

export const home_feature_local_title = /** @type {(inputs: Home_Feature_Local_TitleInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Open local MDX`)
};

export const home_feature_local_description = /** @type {(inputs: Home_Feature_Local_DescriptionInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Preview .mdx and .md files from your machine without publishing them to a cloud service.`)
};

export const home_feature_docs_title = /** @type {(inputs: Home_Feature_Docs_TitleInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Docs-like reading UI`)
};

export const home_feature_docs_description = /** @type {(inputs: Home_Feature_Docs_DescriptionInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Render AI-generated documents with a polished navigation, outline, and reading experience.`)
};

export const home_feature_safe_title = /** @type {(inputs: Home_Feature_Safe_TitleInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Controlled rendering`)
};

export const home_feature_safe_description = /** @type {(inputs: Home_Feature_Safe_DescriptionInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Use a curated component surface so generated MDX stays safe, predictable, and reviewable.`)
};