import { buttonVariants } from '@mdxforge/ui/components/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@mdxforge/ui/components/card'
import { cn } from '@mdxforge/ui/lib/utils'
import {
  IconBook2,
  IconBrandGithub,
  IconDeviceDesktop,
  IconFileTypeTsx,
  IconShieldCheck
} from '@tabler/icons-react'
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  head: () => ({
    meta: [
      { title: 'MDXForge - Preview AI-generated MDX locally' },
      {
        name: 'description',
        content:
          'A focused desktop reader for opening, navigating, and safely rendering local MDX and Markdown files generated by AI.'
      }
    ]
  }),
  component: HomePage
})

const features = [
  {
    title: 'Open local MDX',
    description:
      'Preview .mdx and .md files from your machine without publishing them to a cloud service.',
    icon: IconFileTypeTsx
  },
  {
    title: 'Docs-like reading UI',
    description:
      'Render AI-generated documents with a polished navigation, outline, and reading experience.',
    icon: IconBook2
  },
  {
    title: 'Controlled rendering',
    description:
      'Use a curated component surface so generated MDX stays safe, predictable, and reviewable.',
    icon: IconShieldCheck
  }
] as const

function HomePage() {
  return (
    <main className="min-h-screen overflow-hidden bg-background">
      <section className="relative border-b">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top,oklch(0.74_0.14_181/.18),transparent_34rem)]" />
        <div className="mx-auto flex max-w-6xl flex-col items-center px-6 py-20 text-center sm:py-28">
          <div className="inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1 text-sm text-muted-foreground shadow-sm">
            <IconDeviceDesktop className="size-4 text-primary" />
            Local-first MDX preview for AI docs
          </div>

          <h1 className="mt-8 max-w-4xl text-balance text-4xl font-semibold tracking-tight sm:text-6xl">
            Turn AI-generated MDX into a safe local reading experience.
          </h1>

          <p className="mt-6 max-w-2xl text-balance text-lg text-muted-foreground">
            MDXForge focuses on one workflow: generate structured MDX or Markdown with AI, open it
            locally, review it comfortably, and share it with confidence.
          </p>

          <div className="mt-10 flex flex-col gap-3 sm:flex-row">
            <a
              href="https://github.com/tszones/MDXforge"
              target="_blank"
              rel="noreferrer"
              className={cn(buttonVariants({ size: 'lg' }), 'gap-2')}
            >
              <IconBrandGithub className="size-4" />
              View GitHub
            </a>
            <a href="#features" className={buttonVariants({ variant: 'outline', size: 'lg' })}>
              Explore features
            </a>
          </div>
        </div>
      </section>

      <section id="features" className="mx-auto max-w-6xl px-6 py-16 sm:py-24">
        <div className="grid gap-4 md:grid-cols-3">
          {features.map((feature) => {
            const Icon = feature.icon
            return (
              <Card key={feature.title} className="bg-card/70">
                <CardHeader>
                  <div className="mb-3 flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <Icon className="size-5" />
                  </div>
                  <CardTitle>{feature.title}</CardTitle>
                  <CardDescription>{feature.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="h-1.5 rounded-full bg-linear-to-r from-primary/60 to-transparent" />
                </CardContent>
              </Card>
            )
          })}
        </div>
      </section>
    </main>
  )
}
